export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  PLANTS: '/plants',
  PLANT_LIVE: (id: string) => `/plants/${id}/live`,
  PLANT_ALARMS: (id: string) => `/plants/${id}/alarms`,
  PLANT_TRENDS: (id: string) => `/plants/${id}/trends`,
  PLANT_REPORTS: (id: string) => `/plants/${id}/reports`,
  PLANT_MAINTENANCE: (id: string) => `/plants/${id}/maintenance`,
  TELEMETRY: '/telemetry',
  TAGS: '/tags',
  DEVICES: '/devices',
  AGENTS: '/agents',
  ORGS: '/orgs',
  USERS: '/users',
  BILLING: '/billing',
  AUDIT_LOGS: '/audit-logs',
  SETTINGS: '/settings',
  AI_INSIGHTS: '/ai-insights',
};
